Fixed class= to ClassName = in Navbar and Footer
OpenCodeEra/first-contribution pull request #9
Opened 2023-09-27 03:14 UTC by Vijay-Gunwant

This is a basic change to the code base. Hence i fixed it

2023-09-27 16:38 UTC, AdarshRawat1 commented
Use this email insead of dummy email -  openera@myyahoo.com

2023-09-27 16:47 UTC, AdarshRawat1 requested changes

2023-09-27 16:47 UTC, AdarshRawat1 commented on .vs/Contribution/FileContentIndex/b4d69a9c-1573-489b-8223-9fbc4ae7b953.vsidx
Avoid including binary files in the PR, as they consume storage space and need to be compiled on each user's computer anyway, making it unnecessary.

2023-09-27 16:47 UTC, AdarshRawat1 commented on .vs/ProjectSettings.json
Make sure to avoid tracking your VS Code configuration files.

2023-09-27 16:47 UTC, AdarshRawat1 commented on .vs/slnx.sqlite
BIN file

2023-09-27 16:47 UTC, AdarshRawat1 commented on pages/components/Footer.js
> +                            <a href="mailto:abc@gmail.com" className="hover:underline hover:text-blue-800">Contact</a>
use - openera@myyahoo.com

2023-09-27 16:47 UTC, AdarshRawat1 commented on .vs/VSWorkspaceState.json
Avoid the tracking of configuration files.

2023-09-27 16:47 UTC, AdarshRawat1 commented on .vs/Contribution/v17/.wsuo
BIN file

2023-09-28 00:19 UTC, Vijay-Gunwant commented on .vs/Contribution/FileContentIndex/b4d69a9c-1573-489b-8223-9fbc4ae7b953.vsidx
Done I added these files to the GitIgnore file

2023-09-28 00:19 UTC, Vijay-Gunwant commented on .vs/ProjectSettings.json
Done

2023-09-28 00:20 UTC, Vijay-Gunwant commented on .vs/slnx.sqlite
Done

2023-09-28 00:20 UTC, Vijay-Gunwant commented on pages/components/Footer.js
> +                            <a href="mailto:abc@gmail.com" className="hover:underline hover:text-blue-800">Contact</a>
Done

2023-09-28 03:33 UTC, AdarshRawat1 commented
@Vijay-Gunwant  kindly address other requested changes . ( Don't track- VS code configuration/ BIN file )

"tracking" a file means keeping a record of changes. To stop Git from tracking a file, add it to `.gitignore`.To stop tracking an already tracked file, use git `rm --cached <file>`.

I'll update the `.gitignore` file so that you don't have to do it from next time.

2023-09-28 10:11 UTC, Vijay-Gunwant commented
> @Vijay-Gunwant kindly address other requested changes . ( Don't track- VS code configuration/ BIN file )
> 
> "tracking" a file means keeping a record of changes. To stop Git from tracking a file, add it to `.gitignore`.To stop tracking an already tracked file, use git `rm --cached <file>`.
> 
> I'll update the `.gitignore` file so that you don't have to do it from next time.

I did update the gitignore file in my last commit including the .vs folder in the gitingore file . As of stopping github to track a file i was not aware about it which i will do in my next commit.Thanks to yout such valuable and calm response

2023-09-28 14:48 UTC, AdarshRawat1 commented
> I did update the gitignore file in my last commit including the .vs folder in the gitingore file. 
Thank you @Vijay-Gunwant for addressing the requested changes. 
> As of stopping github to track a file i was not aware about it which i will do in my next commit.Thanks to yout such valuable and calm response
Anytime!

2023-09-28 15:01 UTC, Vijay-Gunwant commented on .vs/Contribution/v17/.wsuo
done

2023-09-28 15:01 UTC, Vijay-Gunwant commented on .vs/VSWorkspaceState.json
done

2023-09-28 15:05 UTC, Vijay-Gunwant commented
> > I did update the gitignore file in my last commit including the .vs folder in the gitingore file.
> 
> Thank you @Vijay-Gunwant for addressing the requested changes. (Kindly mark the requested changes as resolved).
> 
> > As of stopping github to track a file i was not aware about it which i will do in my next commit.
> 
> Now that you have added the VS Code directory in `.gitignore` they won't be tracked so no worries. I also updated the `.gitignore` in main branch so make sure to sync your fork.
> 
> > Thanks to yout such valuable and calm response
> 
> Anytime!

I have marked them and would now you merge this pull request?

2023-09-30 04:11 UTC, merged